### ISSUE TITLE
Got an unexpected error

### ISSUE THREAD

**Issue by TheGenocides** [islamic-network/alquran.cloud#39]
Hey there i was using python to retrieve data from `/quran` endpoint. I got this error:
```
Traceback (most recent call last):
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/urllib3/response.py", line 1077, in read_chunked
    self._update_chunk_length()
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/urllib3/response.py", line 1012, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/urllib3/response.py", line 937, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/urllib3/response.py", line 1065, in read_chunked
    with self._error_catcher():
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    quran = client.fetch_quran()
  File "/home/runner/holybooks/holybooks/client.py", line 22, in fetch_quran
    return self.fetch_book(translation=translation)
  File "/home/runner/holybooks/holybooks/http.py", line 78, in fetch_book
    res = self.request(url)
  File "/home/runner/holybooks/holybooks/http.py", line 51, in request
    res = req(url)
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/runner/holybooks/venv/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
Im using requests library.  Might have a hint of why? I think it isnt because of the site.

**Comment by meezaan** [comment]
It looks like your connection was interrupted during the download. Perhaps an IP changed or there was a VPN connection that got reset or there was some issue with the connectivity.

Or there is some firewall the machine that got in the way?

**Comment by TheGenocides** [comment]
> It looks like your connection was interrupted during the download. Perhaps an IP changed or there was a VPN connection that got reset or there was some issue with the connectivity.
> 
> Or there is some firewall the machine that got in the way?

But it seems the the other url with different edition works. `https://api.alquran.cloud/v1/quran/en` this caused the error while `https://api.alquran.cloud/v1/quran/id.indonesian` or `https://api.alquran.cloud/v1/quran/en.assad` does not. So i dont think any of those reasons are why the error was raised.

**Comment by meezaan** [comment]
That's because the first url does not exist. There is no edition called 'en'.

**Comment by TheGenocides** [comment]
> That's because the first url does not exist. There is no edition called 'en'.

![image](https://user-images.githubusercontent.com/82718066/250291359-db36d251-a19f-4f9f-bce2-2b2522918b7a.png) seems to work, i tried this url: `https://api.alquran.cloud/v1/quran/en`

**Comment by meezaan** [comment]
It returns the default edition - but it's definitely not the one you want when you pass en.

Keep in mind that firewalls and anti virus software are known to throttle http streams that include Arabic or Persian characters they don't recognize. So you may want to turn any of these off if your connection gets interrupted randomly.

**Comment by TheGenocides** [comment]
> It returns the default edition - but it's definitely not the one you want when you pass en.
> 
> Keep in mind that firewalls and anti virus software are known to throttle http streams that include Arabic or Persian characters they don't recognize. So you may want to turn any of these off if your connection gets interrupted randomly.

I see thanks for your answer! I'll close this issue.
